package com.tactical.privacy.models;

public enum StepType {
    IDENTITY_USER_DELETE,
    THIRD_PARTY_CUSTOMERS_DELETE,
    SUBSCRIBER_MAIN_MYSQL_DELETE,
    SUBSCRIBER_GEOLOCATION_DELETE,
    SUBSCRIBER_EVENTS_DELETE,
    CARRIER_INFO_DELETE
}